
version: '3'

services: 
  mongodb-fabrica:
    image: bitnami/mongodb:latest
    networks: 
      - mongodb_network
    volumes:
      - mongodb_data:/bitnami
    ports:
      - "27017:27017"
    environment: 
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
  
  admin-api:
    image: "node:10-slim"
    networks:
      - base_network
      - mongodb_network
    ports: 
      - "3001:3001"
    working_dir: /app
    command: sh -c "yarn && yarn dev"
    depends_on: 
      - mongodb-fabrica
    volumes: 
      - ./admin-api:/app
    environment:
      NODE_ENV: development
      MONGO_URI: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_ADDRESS}:27017/${MONGODB_DATABASE}" 
      SECRET_HASH: ${SECRET_HASH}
      SECRET_REFRESH_HASH: ${SECRET_REFRESH_HASH}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_STORAGE_BUCKET: ${GOOGLE_STORAGE_BUCKET}

  admin-client:
    image: "node:10-slim"
    networks:
      - base_network
    ports:
      - "3000:3000"
    command: sh -c "yarn && yarn dev"
    working_dir: /app
    volumes:
      - ./admin-client:/app
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      API_URL: ${ADMIN_API_URL}
      TOKEN: ${TOKEN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      SECRET_LOCAL_KEY: ${SECRET_LOCAL_KEY}
  
  user-client:
    image: "node:10-slim"
    networks:
      - base_network
    ports:
      - "3001:3000"
    command: sh -c "yarn && yarn dev"
    working_dir: /app
    volumes:
      - ./user-client:/app
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      API_URL: ${ADMIN_API_URL}
      TOKEN: ${TOKEN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      SECRET_LOCAL_KEY: ${SECRET_LOCAL_KEY}

networks:
  base_network:
  mongodb_network:

volumes: 
  mongodb_data:
  admin-client:
  admin-api:
  user-client: